### PR TITLE
Enemy AI System

### PR DESCRIPTION
**Pull request by Anonymous4045**
This PR will change a lot of things in order to make enemies behave as they should.

This changes the physics engine from Platformer to Pymunk, which is a pretty big change, but I think it's the only (good) way for the enemy sprites to get the features we need, such as obeying gravity.

It also gives the enemies senses and motive. When the enemy detects the player, it goes into attack mode and targets them. It currently doesn't deal damage, as that was requested in another issue.

Each enemy has two "senses": touch and sight. When the player touches an enemy or goes into the enemy's line of sight, the enemy attacks.

### CODE REVIEW

**Comment by ilcheese2** [comment]
I was just about to work on a pr for pymunk. Switching to it seems like a good idea since it allows for more control and makes the movements feel more realistic instead of forced.

**Review by shenanigansd — DISMISSED** [review]

**Review by FieryIceStickie — CHANGES_REQUESTED** [review]
After each jump there's a bounce in the player, and that causes the next jump to be eaten and I don't think that's very natural.
Other than that LGTM
Also i'm personally in favour of replacing W with space for jump instead, so space and uparrow for jump, any opinions?

**Comment by Anonymous4045** [comment]
> i'm personally in favour of replacing W with space for jump instead, so space and uparrow for jump

Yeah I think space for jump is more natural. That's beyond the scope of this pr though. I'll fix the bouncing thing when I can.

**Review by FieryIceStickie — APPROVED** [review]

**Review by FieryIceStickie — CHANGES_REQUESTED** [review]
imports from constant.py doesn't work

**Comment by Robin5605** [comment]
The traceback from @FieryIceStickie 's comment:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/robin/Desktop/Coding/pyweek-2023-03/src/pyweek-2023-03/__main__.py", line 9, in <module>
    from .game_view import GameView
  File "/home/robin/Desktop/Coding/pyweek-2023-03/src/pyweek-2023-03/game_view.py", line 7, in <module>
    from .constants import GRAVITY, TILE_SCALING, PLAYER_JUMP_IMPULSE, PLAYER_JUMP_SPEED, PLAYER_MOVEMENT_SPEED, \
ImportError: cannot import name 'PLAYER_JUMP_IMPULSE' from 'src.pyweek-2023-03.constants' (/home/robin/Desktop/Coding/pyweek-2023-03/src/pyweek-2023-03/constants.py)
```

**Review by FieryIceStickie — APPROVED** [review]

**Review by shenanigansd — DISMISSED** [review]

**Pull request merged**
